# Generated by Django 2.1.3 on 2018-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Numer tygodnia.')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Przebyty dystans.')),
                ('ride_time', models.TimeField(verbose_name='Czas jazdy.')),
                ('max_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Maksymalna prędkość')),
                ('average_speed', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Średnia prędkość.')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Kalorie.')),
                ('f_calories', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='F_kalorie.')),
            ],
        ),
    ]
